# Generated by Django 4.2.7 on 2023-12-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_created_product_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
