# Generated by Django 4.2.7 on 2023-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_rename_updated_service_modified_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
