# Generated by Django 4.2.7 on 2023-12-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_categorypost_delete_category_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
